### ISSUE TITLE
[SDKTECHNO-54] Azure Data Factory

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/technologies#135]
In the past customer meetings i had more than 5 times Azure Data factory has come up and it seems to be used almost as default any one using Azure.

**Comment by ntorionbearstudio** [comment]
## Azure Data Factory integration

**Pipelines context**

- [ ] List Data Factories

- [ ] List Data Factory pipelines

- [ ] Start Data Factory pipeline

- [ ] Stop Data Factory pipeline

- [ ] Get status of Data Factory pipeline

- [ ] Get logs of Data Factory pipeline
