### ISSUE TITLE
[SDKTECHNO-65] Trifacta 7.1

### ISSUE THREAD

**Issue by Jo314** [saagie/technologies#157]

**Comment by ntorionbearstudio** [comment]
To do

On existing contexts inside current Trifacta integration (v+6.4)

- [ ] Add the Stop action on current integration

- [ ] Rename the default context as "Flow context" (version +6.4)

Create a new context "Plans context" (only for 7.1 version) this a new entity that can be run (several flows combined) :

- [ ] List plans

- [ ] Run selected plan

- [ ] Get plan run status

- [ ] Get plan run logs
