### ISSUE TITLE
[SDKTECHNO-66] Issue on PySpark 3.0

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#158]
Support ticket : 

La version python de spark 3.0 ne fonctionne pas. Le job ne récupère pas dans le Minio les assets.

Jobs : 
Spark 3.0 KO : https://saagie-workspace.prod.saagie.io/projects/platform/6/project/8321e13c-892a-4481-8552-5be4b6cc5df4/job/896a12ca-a9b8-4c77-8d79-b206dba02eb1/instances/d276a299-fb58-424d-8556-e1b79d18dccd
Spark 2.4 OK : https://saagie-workspace.prod.saagie.io/projects/platform/6/project/8321e13c-892a-4481-8552-5be4b6cc5df4/job/9f2451b1-b9a1-4310-8fa7-4c4af37e98b1/instances/0a1932bc-80bc-4903-a940-9a86faedf214

Dans les logs, ligne 10, on voit que le SPARK_K8S_CMD est différent entre les 2 versions. Et la ligne 20 on voit qu'il manque l'URL du minio manquante.

**Comment by finalspy** [comment]
Closed by #160
