### ISSUE TITLE
[SDKTECHNO-80] Update technologies README (only for Saagie Repository):

### ISSUE THREAD

**Issue by Jo314** [saagie/technologies#191]
* with links to Saagie official documentation
* keep legacy documentation

**Comment by finalspy** [comment]
On docker hub replace by generic text pointing to Oficial Saagie documentation and github source repository.
On github, update documentation to match current version. (legacy documentation will remain available in git history if necessary)

**Comment by finalspy** [comment]
Docker  descriptions updated on dockerhub and saved in the technologies dictory under dockerhub.md for the following technologies : 
- rstudio
- jupyter-python-nbk
- zeppelin-nbk
- nifi
- kibana

Changes made on the current dev branches for toucantoco and cloudbeaver.
