### ISSUE TITLE
[ToucanToco]Impossible d'avoir 2 fois l'application Toucan Toco fonctionnelle.

### ISSUE THREAD

**Issue by EtienneSIG** [saagie/technologies#252]
Bonjour,

L'utilisation de manière unitaire de l'application toucan toco fonctionne bien (au delta de certain bouton de retour en arrière qui renvoie à Saagie et non à Toucan Toco)

Lors de l'ajout d'une deuxième image dans un autre projet (ou dans le même), l'application est bien pullé mais impossible de se connecter dessus. On obtient le message d'erreur suivant : "Une erreur inattendue s'est produite (Error: Unable to log)." (cf. screenshot)
<img width="436" alt="Capture d’écran 2021-01-29 à 14 23 12" src="https://user-images.githubusercontent.com/25098838/106279947-88a56580-623d-11eb-8fc8-659985e06e2e.png">

Le problème ne vient pas du user/pwd car le message d'erreur est différent dans le cas d'un mauvais user/pwd (cf.screenshot ci-dessous)
<img width="414" alt="Capture d’écran 2021-01-29 à 14 24 34" src="https://user-images.githubusercontent.com/25098838/106280087-b8546d80-623d-11eb-9970-1ef6e89d8651.png">

N'hésites pas à revenir vers moi si je n'ai pas été assez précis.

**Comment by finalspy** [comment]
Merci d'ouvrir une issue sur les boutons retour qui ne fonctionnent pas correctement en précisant les écrans et conditions de reproduction svp

**Comment by finalspy** [comment]
Dans un même projet il ne sera pas possible de rajouter une deuxième instance de Toucantoco, ni de la plupart des apps du moment qu’elles nécessitent des variables d'environnement, du simple fait que ces variables sont communes au projet et non a l'app. 
Ce soucis ne vient pas des images mais du produit, il faut donc plutôt ouvrir une issue ou une demande ADR etc vers le produit pour demander a avoir des variables d'environnement par App et non par Projet. 
Sujet a discuter avec la feature team app-refacto par exemple.

**Comment by EtienneSIG** [comment]
> Dans un même projet il ne sera pas possible de rajouter une deuxième instance de Toucantoco, ni de la plupart des apps du moment qu’elles nécessitent des variables d'environnement, du simple fait que ces variables sont communes au projet et non a l'app.
> Ce soucis ne vient pas des images mais du produit, il faut donc plutôt ouvrir une issue ou une demande ADR etc vers le produit pour demander a avoir des variables d'environnement par App et non par Projet.
> Sujet a discuter avec la feature team app-refacto par exemple.

Ok, pour dans le même projet. Mais quand c'est 2 projets différents ont a le même problème quelque soit la platforme (demo-workspace.a4.saagie.io et saagie-workspace.prod.saagie.io)

**Comment by finalspy** [comment]
Enfin si l'onparle d'un second projet, pour le soucis de l'erreur inattendue, cela peut avoir a mon avis 4 origines : 

- Soit le back-end Toucan n'est pas encore totalement lancé et il faut attendre quelques minutes et recommencer. (malheureusement a ce jour pas de moyen de savoir quand il est opérationnel dans l'IHM Saagie).
- Soit les variables d'environnement TOUCAN_HOST TOUCAN_BACK_PORT et TOUCAN_DB_ENCRYPTION_SECRET n'ont pas été redéfinies dans le nouveau projet, car oui il faut les dupliquer puisque leur portée est par projet.
- Soit la configuration de l'app n'est pas correcte,
- Soit enfin il peut s'agir d'une collision de cookies de domaine, dans ce cas nous ne pourrons rien faire, juste indiquer qu'une seule instance de l'application fonctionne par utilisateur/navigateur. (Tu peux tester si c'est ce cas de figure en ouvrant tes applications depuis 2 navigateurs diff2rents ou en mode navigation privée éventuellement).

**Comment by EtienneSIG** [comment]
> Enfin si l'on parle d'un second projet, pour le soucis de l'erreur inattendue, cela peut avoir a mon avis 4 origines :
> 
> * Soit le back-end Toucan n'est pas encore totalement lancé et il faut attendre quelques minutes et recommencer. (malheureusement a ce jour pas de moyen de savoir quand il est opérationnel dans l'IHM Saagie).
> * Soit les variables d'environnement TOUCAN_HOST TOUCAN_BACK_PORT et TOUCAN_DB_ENCRYPTION_SECRET n'ont pas été redéfinies dans le nouveau projet, car oui il faut les dupliquer puisque leur portée est par projet.
> * Soit la configuration de l'app n'est pas correcte.
> * Soit enfin il peut s'agir d'une collision de cookies de domaine, dans ce cas nous ne pourrons rien faire, juste indiquer dans la documentation qu'une seule instance de l'application fonctionne par utilisateur/navigateur. (Tu peux tester si c'est ce cas de figure en ouvrant tes applications depuis 2 navigateurs diff2rents ou en mode navigation privée éventuellement).

Pour la conf de l'app, je l'ai fait à l'identique de ce qu'on avait fait et quand je supprime toutes les applications et que je recrée l'app. j'ai le meme comportement à chaque fois à partir de la deuxième instanciation de l'app

**Comment by finalspy** [comment]
Test effectue sur un navigateur fiirefox reproduit le probleme, a savoir que si l'on se loggue sur une seconde instance de Toucantoco (quand on se loggue uniquement, les 2 instances peuvent demarrer en parallele sans soucis), alors la premiere instance sur laquelle on s'est loggue devient non fonctionnel. 

Comportement reproduit en navigation privee.

Comportement non reproduit si les 2 instances de toucantoco sont ouvertes dans 2 navigateurs differents : chrome pour l'un et firefox pour l'autre.

Mise en evidence au login toucan du positionnement d'une cle de LocalStorage (donc propre a un navigateur), sur le domaine de la pf Saagie.
Ainsi si on se loggue sur le premier Toucan, il cree disons une cle AAA. 
2 cas de figure : 
- soit la page de login vers le 2eme toucan n'est pas ouverte et a ce moment la lorsqu'on l'ouvre il n reconnait pas la cle de local storage et provoque une deconnexion du premier toucan car il supprime la cle, et redirige car en erreur vers le projet Saagie (peut etre faut il intercepter l'URL pour rediriger vers une erreur interne toucan).
- soit la page de login est deja ouverte et ne lit donc pas la nouvelle cle du precedent login, et autorise un nouveau login, aui genere une nouvelle cle ecrasant la premiere , dans ce cas le second toucan est fonctionnel mais le premier "plante" ne reconnaissant pas sa cle, il supprime alors la cle inconnue ce qui provoaue le logout du second toucan...

Si l'on utilise 2 navigateurs differents les toucantocos ne s'ecrasent ou ne s'effacent pas mutuellement les cles de localstorage.

Ce probleme est inherent a la facon dont l'application Toucantoco est construite, Saagie ne peut rien y faire. 

Je clos ce probleme et j'ajoute une note dans Notion indiquant que seul 1 instance Toucan par navigateur est autorisee ndependamment du projet Saagie. 

(Note que 2 toucan peuvent coexister sur 2 pf distinctes et etre appeles au sein d'un meme navigateur la cle etant liee au domaine de connexion... )
