### ISSUE TITLE
[Cloudbeaver]Problème d'icone lors du chargement des bases de données ou de l'execution d'une requête

### ISSUE THREAD

**Issue by EtienneSIG** [saagie/technologies#253]
Bonjour, 

je pense que un lien vers les icônes est mal recrée. On constate lors du déroulement des databases ou de l'exécution d'une requête. 

<img width="1440" alt="Capture d’écran 2021-01-29 à 14 28 58" src="https://user-images.githubusercontent.com/25098838/106280570-67914480-623e-11eb-9437-c66e406dc140.png">

**Comment by finalspy** [comment]
tu parles de l'icone de loading ? ou y a t'il aute chose ?

**Comment by EtienneSIG** [comment]
Oui je parle juste de l'icône de loading.

**Comment by finalspy** [comment]
Ok reproduit, correctif possible a priori
