### ISSUE TITLE
[SDKTECHNO-4] Trifacta

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#30]
Access to Trifacta is here : https://www.notion.so/saagie/Trifacta-6a9c241eee564b8a907a052052e0f849

Old integration code : https://github.com/saagie/proto-job-integration

**Comment by ntorionbearstudio** [comment]
- [ ] Connect platform to Trifacta API
- [ ] Find a way to identify user to Trifacta on requests
- [ ] Retrieve datasets
- [ ] Run job
- [ ] Stop job
- [ ] Get job logs
- [ ] Get job status

**Comment by ntorionbearstudio** [comment]
https://github.com/saagie/technologies/pull/64

**Comment by ntorionbearstudio** [comment]
Documentation for integration

**Comment by ntorionbearstudio** [comment]
To do after feedbacks :

- [ ] Add optional field for setting custom `writingSettings` when running a job

- [ ] Add optional select for listing available `writingSettings` configs for a wrangled dataset when running a job

- [ ] Fix axios error gestion (convert to node Error object)

- [ ] Add errors messages more specifics
