### ISSUE TITLE
[SDKTECHNO-10] Informatica Cloud Data Integration

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#39]
https://docs.informatica.com/integration-cloud/cloud-data-integration.html

**Comment by ntorionbearstudio** [comment]
https://docs.informatica.com/integration-cloud/cloud-platform/current-version/rest-api-reference/preface.html#

**Comment by ntorionbearstudio** [comment]
https://www.notion.so/Informatica-integration-db4792ef118c42aa876ed2fb2d6c3971

**Comment by ntorionbearstudio** [comment]
Informatica Cloud platform integration

Context REST API v3

- [x]  Retrieve projects
- [x]  Retrieve folders
- [x]  Retrieve tasks
- [x]  Run job
- [x]  Get job status
- [x]  Get job logs
- [ ]  Manage errors
- [ ]  Create required enums
- [ ]  Avoid code duplications

Context REST API v2

- [ ]  Retrieve all tasks
- [ ]  Run job
- [ ]  Get job status
- [ ]  Get job logs
- [ ]  Manage errors
- [ ]  Create required enums
- [ ]  Avoid code duplications
