### ISSUE TITLE
[SDKTECHNO-11] Knime

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#40]
Old integration code https://github.com/saagie/proto-job-integration

**Comment by ntorionbearstudio** [comment]
https://www.knime.com/blog/the-knime-server-rest-api

**Comment by ntorionbearstudio** [comment]
Server configured : https://184.73.16.189/knime/

**Comment by ntorionbearstudio** [comment]
Integration documentation : https://www.notion.so/Knime-integration-e0fc8fb3773242e5ac3cf673a360de84

**Comment by ntorionbearstudio** [comment]
https://docs.knime.com/2018-12/server_admin_guide/index.html#log-files

**Comment by ntorionbearstudio** [comment]
Knime integration :

- [x] Retrieve workflow groups
- [x] Retrieve workflows
- [x] Retrieve workflow jobs
- [x] Run job
- [x] Get status
- [ ] Get logs
- [ ] Manage errors
- [ ] Create required enums
- [ ] Avoid code duplications
