### ISSUE TITLE
[SDKTECHNO-19] Dataiku

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#48]
Old integration code https://github.com/saagie/proto-job-integration

**Comment by ntorionbearstudio** [comment]
Documentation : https://www.notion.so/Dataiku-27fe21a919294f54ae0a5681876aa712

**Comment by ntorionbearstudio** [comment]
To do

- [ ]  Retrieve projects
- [ ]  Retrieve datasets
- [ ]  Run job
- [ ]  Get job status
- [ ]  Get job logs
- [ ]  Manage errors
- [ ]  Create required enums
- [ ]  Avoid code duplications
- [ ]  Add Data integration label to context
