### ISSUE TITLE
[SDKTECHNO-198] Add S3 Browser

### ISSUE THREAD

**Issue by tquiviger** [saagie/technologies#485]
Add a S3 browser as an App
(maybe fork https://github.com/cloudlena/s3manager)

**Comment by github-saagie** [comment]
Trello card: [[#485] Add S3 Broswer](https://trello.com/c/TdZNAZXd)

**Comment by tquiviger** [comment]
No official s3 browser found, users should use app such as Cyberduck, ExpanDrive or AWSToolkit within VSCode
