### ISSUE TITLE
[SDKTECHNO-20] GCP Cloud Run

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#50]

**Comment by ntorionbearstudio** [comment]
**New service context**

- [ ] Start / Create service

- [ ] Stop / Remove service

- [ ] Get service status

- [ ] Get service logs

**Clone services context**

- [ ] List services

- [ ] Clone service

- [ ] Stop / Remove service

- [ ] Get service status

- [ ] Get service logs

**Comment by ntorionbearstudio** [comment]
Changements after review :

- [ ] Add error gestion for service name format
- [ ] Add error gestion for service name already existing
- [ ] Change label name for "copied service name"
- [ ] Remove stop actions
- [ ] Add params (autoscale + ports)
