### ISSUE TITLE
[SDKTECHNO-206] Add the aws.s3 library modified by Saagie in the R images

### ISSUE THREAD

**Issue by TFellet** [saagie/technologies#504]
The official aws.s3 library doesn't work with OVH S3, this has been fixed by Saagie in a fork. 
This issue tracks the integration of this forked library in the official Saagie R images

**Comment by github-saagie** [comment]
Trello card: [[#504] Add the aws.s3 library modified by Saagie in the R images](https://trello.com/c/jfNy7zb3)
