### ISSUE TITLE
[SDKTECHNO-22] Azure Databricks

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#51]

**Comment by ntorionbearstudio** [comment]
- [x]  Retrieve resource groups
- [x]  Retrieve workspaces
- [x]  Retrieve jobs
- [x]  Run job
- [x]  Stop job
- [x]  Get job status
- [ ]  Get job logs
- [ ]  Manage errors
- [x]  Create required enums
- [x]  Avoid code duplications
