### ISSUE TITLE
[SDKTECHNO-23] Azure Functions

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#52]

**Comment by ntorionbearstudio** [comment]
https://docs.microsoft.com/fr-fr/azure/azure-functions/functions-overview

**Comment by ntorionbearstudio** [comment]
https://www.notion.so/Azure-Functions-36bbe8acd85b45cfabe04dcf7d7e9149

**Comment by ntorionbearstudio** [comment]
To do

- [x]  Retrieve resource groups
- [x]  Retrieve function apps
- [x]  Retrieve functions
- [x]  Enable function
- [x]  Disable function
- [x]  Get function status
- [x]  Get function logs
- [x]  Manage errors
- [x]  Create required enums
- [x]  Avoid code duplications
