### ISSUE TITLE
[SDKTECHNO-24] Azure ML

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#53]

**Comment by ntorionbearstudio** [comment]
https://www.notion.so/Azure-ML-4c73e499520f4badb47e61ba9642fefe

**Comment by ntorionbearstudio** [comment]
https://docs.microsoft.com/en-us/rest/api/azureml/

**Comment by ntorionbearstudio** [comment]
Based on Azure ML platform tests and on API documentation it seems that we can integrate two contexts :

- **Pipelines context** :

Pipelines are automated tasks that can integrate datasets and ML models

Actions to integrate :

- [ ] pipelines runs listing
- [ ] re-run pipeline
- [ ] stop pipeline
- [ ] get pipeline status
- [ ] get pipeline logs

- **Automated ML context** :

Automated ML train and find the best model based on your data without writing a single line of code.
Automated ML are automated tasks to create models

- [ ] create a new automated ML run by passing JSON description and a zip file
- [ ] get run status
- [ ] stop run
- [ ] get run logs

**Comment by ntorionbearstudio** [comment]
Requested changements on meeting :

- Create new context : resubmit experimental run
- Add input for specifing params on pipelines runs submit

**Comment by ntorionbearstudio** [comment]
> Requested changements on meeting :
> 
> * Create new context : resubmit experimental run
> * Add input for specifing params on pipelines runs submit

Create new context : resubmit experimental run => not integrable for the moment because rerun action for experiments runs is not working on Azure Portal (no sended request) and no request details inside REST API documentation

**Comment by ntorionbearstudio** [comment]
After review :

Azure ML Automated ML : Actions OK but validation NOK, I have to investigate why Automated ML runs stay always in queued status
