### ISSUE TITLE
[SDKTECHNO-213] Add boto3 into Mlflow-server apps

### ISSUE THREAD

**Issue by HugoPoupon** [saagie/technologies#530]
**Is your feature request related to a problem? Please describe.**
Need to install the boto3 python library inside the MlFlow-Server image to be able to interact with it in jobs

**Describe the solution you'd like**
Add "pip install boto3" command inside MlFlow Dockerfile

**Comment by github-saagie** [comment]
Trello card: [[#530] Add boto3 into Mlflow-server apps](https://trello.com/c/YS74yOn7)
