### ISSUE TITLE
[SDKTECHNO-218] Error SUM hard password

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies#537]
SUM doesn'l work when you put a strong password like : 
3yfaZG89%NpypAnKh7f%tA%*uo6%wB#uvmUtP@7YMb*oq2KcCBU4yr8tCyVwffLmc3Mb!Wwn%N^^m&9$62qo6!%Ax#XUeY&w9*jp$gbbnGiQXy$FrC^AjDXSngXm2iq4

**Comment by github-saagie** [comment]
Trello card: [[#537] Error SUM hard password](https://trello.com/c/TYvOdoSp)
