### ISSUE TITLE
[SDKTECHNO-228] Fix python 3.7

### ISSUE THREAD

**Issue by Qiwei08** [saagie/technologies#568]
Fix  python 3.7 to use image saagie/python:1.46.0_SDKTECHNO-63 because image  saagie/python:3.7-1.137.0_SDKTECHNO-205 doesn't contains some librairies like: boto3

**Comment by github-saagie** [comment]
Trello card: [[#568] Fix python 3.7](https://trello.com/c/kuscAj5k)
