### ISSUE TITLE
[SDKTECHNO-28] GCP Kubeflow

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#57]

**Comment by ntorionbearstudio** [comment]
**Pipelines context**

- [ ] List Kubeflow instances

- [ ] List pipelines

- [ ] List experiments

- [ ] Start a new run for selected pipeline

- [ ] Stop the started run

- [ ] Get run status

- [ ] Get run logs

**Comment by ntorionbearstudio** [comment]
Notion documentation on integration :

https://www.notion.so/GCP-Kubeflow-8b0fc48cbb8548819590fa48e57ad916
