### ISSUE TITLE
[SDKTECHNO-239] Hive Connection R KO

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies#593]
There is a problem to connect to Hive from R 4.1+.

Suggestions of modifications : 
sudo apt-get update
sudo apt-get install -yqq --no-install-recommends libsasl2-modules-gssapi-mit unixodbc

wget https://downloads.cloudera.com/connectors/ClouderaHive_ODBC_2.6.16/Debian/clouderahiveodbc_2.6.16.1019-2_amd64.deb
sudo dpkg -i clouderahiveodbc_2.6.16.1019-2_amd64.deb

sudo odbcinst -i -d -f /opt/cloudera/hiveodbc/Setup/odbcinst.ini

sudo sed -i 's/ODBCInstLib=libiodbcinst.so/ODBCInstLib=\/usr\/lib\/x86_64-linux-gnu\/libodbcinst.so/g' /opt/cloudera/hiveodbc/lib/64/cloudera.hiveodbc.ini

**Comment by github-saagie** [comment]
Trello card: [[#593] Hive Connection R KO](https://trello.com/c/niPIQ2mu)
