### ISSUE TITLE
[SDKTECHNO-31] GCP Cloud Data Fusion

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#60]

**Comment by ntorionbearstudio** [comment]
**Pipelines context**

- [ ] List GCP Cloud Data Fusion service regions

- [ ] List GCP Cloud Data Fusion instances

- [ ] List GCP Cloud Data Fusion pipelines in selected instance

- [ ] Start selected pipeline

- [ ] Stop selected pipeline

- [ ] Get selected pipeline status

- [ ] Get selected pipeline logs

**Comment by ntorionbearstudio** [comment]
https://www.notion.so/GCP-Cloud-Data-Fusion-8ca6b266437c4e9abceeafab5ae07d98
