### ISSUE TITLE
[SDKTECHNO-257] Fix environement variable Grafana

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies#629]
Fix environement variable mandatory for technology Grafana. In Readme file variable GF_SECURITY_ADMIN_PASSWORD but in entrypoint it is GF_SECURITY_ADMIN_PASSWORD.

**Comment by github-saagie** [comment]
Trello card: [[#629] Fix environement variable Grafana](https://trello.com/c/oAe5Nbqc)

**Comment by zannelo** [comment]
Je peux embarquer cette modification avec ma PR si vous voulez : https://github.com/saagie/technologies/pull/635

**Comment by zannelo** [comment]
Embarqué dans la PR https://github.com/saagie/technologies/pull/635.

**Comment by zannelo** [comment]
Embarqué dans la PR https://github.com/saagie/technologies/pull/635.
