### ISSUE TITLE
[SDKTECHNO-267] Modify SMT_MAX_INSTANCES_FETCHED to SUM_MAX_INSTANCES_FETCHED

### ISSUE THREAD

**Issue by annelhomme** [saagie/technologies#651]
**Is your feature request related to a problem? Please describe.**
Change variable name

**Describe the solution you'd like**
Need to rename SMT_MAX_INSTANCES_FETCHED to SUM_MAX_INSTANCES_FETCHED

**Describe alternatives you've considered**

**Additional context**
already implemented but not with the good syntax.

**Comment by github-saagie** [comment]
Trello card: [[#651] Modify SMT_MAX_INSTANCES_FETCHED to SUM_MAX_INSTANCES_FETCHED](https://trello.com/c/Dgtsqbhn)

**Comment by annelhomme** [comment]
fait sur SDKTECHNO-268
