### ISSUE TITLE
[SDKTECHNO-38] Informatica Powercenter (SOAP)

### ISSUE THREAD

**Issue by youenchene** [saagie/technologies#75]
https://docs.informatica.com/data-integration/powercenter/10-2.html

Using SOAP API

Version to manage : 10.2

Docker : https://docs.informatica.com/data-integration/powercenter/h2l/how-to-install-informatica-using-a-docker-utility/how-to-install-informatica-using-a-docker-utility/build-the-informatica-docker-image.html

**Comment by ntorionbearstudio** [comment]
Informatica Powercenter SOAP integration

- [ ]  Retrieve repositories
- [ ]  Retrieve folders
- [ ]  Retrieve workflows
- [ ]  Run workflow
- [ ]  Get job status
- [ ]  Get job logs
- [ ]  Get job logs when logs are in ZIP file
- [ ]  Manage errors
- [ ]  Create required enums
- [ ]  Avoid code duplications
- [ ]  Add Data integration label to context
